vim.opt.background = 'dark'
vim.g.colors_name = 'karonda'
-- By setting our module to nil, we clear lua's cache,
-- which means the require ahead will *always* occur.
-- The performance impact of this call can be measured in the hundreds of
-- *nanoseconds* and such could be considered "production safe".
package.loaded['lush_theme.karonda'] = nil
-- include our theme file and pass it to lush to apply
-- PATCH_OPEN
-- Generated by lush builder on Fri Apr  1 18:59:59 2022
--
-- You can configure how this build function operates by passing in optional
-- function handlers via the options table.
--
-- See each default handler below for guidance on writing your own.
--
-- {
--   configure_group_fn = function(group) ... end,
--   generate_group_fn = function(group) .. end,
--   before_apply_fn = function(rules) ... end,
--   apply_fn = function(rules) ... end,
-- }
local lush_groups = {
  {
    name = 'Type',
    type = 'group',
    data = {
      fg = '#CDFA05',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'ColorColumn',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = '#1A1A1A',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Conceal',
    type = 'group',
    data = {
      fg = '#1A1A1A',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'CursorColumn',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = '#171717',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'CursorLine',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = '#121212',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Directory',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'DiffAdd',
    type = 'group',
    data = {
      fg = '#CDFA05',
      bg = '#293201',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'DiffChange',
    type = 'group',
    data = {
      fg = '#F7CF1D',
      bg = '#312902',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'DiffDelete',
    type = 'group',
    data = {
      fg = '#FF120A',
      bg = '#330200',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'DiffText',
    type = 'group',
    data = {
      fg = '#FF6600',
      bg = '#331400',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'EndOfBuffer',
    type = 'group',
    data = {
      fg = '#1A1A1A',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'VertSplit',
    type = 'group',
    data = {
      fg = '#171717',
      bg = 'none',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Folded',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = '#333333',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'FoldColumn',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = '#333333',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'SignColumn',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Substitute',
    type = 'group',
    data = {
      fg = '#FF6600',
      bg = '#331400',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'LineNr',
    type = 'group',
    data = {
      fg = '#333333',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'CursorLineNr',
    type = 'group',
    data = {
      fg = '#B3B3B3',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'MatchParen',
    type = 'group',
    data = {
      fg = '#F7CF1D',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'bold',
      blend = 'NONE'
    }
  }, {
    name = 'ModeMsg',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'MsgArea',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'MoreMsg',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'NonText',
    type = 'group',
    data = {
      fg = '#616161',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Normal',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'NormalNC',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Pmenu',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = '#1A1A1A',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'PmenuSel',
    type = 'group',
    data = {
      fg = '#000000',
      bg = '#E6E6E6',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'PmenuSbar',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = '#333333',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'PmenuThumb',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = '#B3B3B3',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Question',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'QuickFixLine',
    type = 'group',
    data = {
      fg = '#FD30A4',
      bg = '#3D0123',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Search',
    type = 'group',
    data = {
      fg = '#FD30A4',
      bg = '#3D0123',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'SpecialKey',
    type = 'group',
    data = {
      fg = '#1A1A1A',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'SpellBad',
    type = 'group',
    data = {
      fg = '#FF120A',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'underline',
      blend = 'NONE'
    }
  }, {
    name = 'SpellCap',
    type = 'group',
    data = {
      fg = '#F7CF1D',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'underline',
      blend = 'NONE'
    }
  }, {
    name = 'Title',
    type = 'group',
    data = {
      fg = '#FD30A4',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Visual',
    type = 'group',
    data = {
      fg = '#000000',
      bg = '#E6E6E6',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'VisualNOS',
    type = 'group',
    data = {
      fg = '#333333',
      bg = '#999999',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Whitespace',
    type = 'group',
    data = {
      fg = '#1A1A1A',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Identifier',
    type = 'group',
    data = {
      fg = '#999999',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Statement',
    type = 'group',
    data = {
      fg = '#B3B3B3',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Conditional',
    type = 'group',
    data = {
      fg = '#EB0075',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Repeat',
    type = 'group',
    data = {
      fg = '#EB0075',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Exception',
    type = 'group',
    data = {
      fg = '#B3B3B3',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'PreProc',
    type = 'group',
    data = {
      fg = '#666666',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Special',
    type = 'group',
    data = {
      fg = '#4D4D4D',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Function',
    type = 'group',
    data = {
      fg = '#CDFA05',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Delimiter',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'SpecialComment',
    type = 'group',
    data = {
      fg = '#F7CF1D',
      bg = '#312902',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Debug',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'NormalFloat',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Bold',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'bold',
      blend = 'NONE'
    }
  }, {
    name = 'Comment',
    type = 'group',
    data = {
      fg = '#333333',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'italic',
      blend = 'NONE'
    }
  }, {
    name = 'Todo',
    type = 'group',
    data = {
      fg = '#F7CF1D',
      bg = '#312902',
      sp = 'NONE',
      gui = 'bold',
      blend = 'NONE'
    }
  }, {
    name = 'ErrorMsg',
    type = 'group',
    data = {
      fg = '#FF120A',
      bg = '#331400',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'DiagnosticError',
    type = 'group',
    data = {
      fg = '#FF120A',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'DiagnosticWarn',
    type = 'group',
    data = {
      fg = '#FF6600',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Keyword',
    type = 'group',
    data = {
      fg = '#999999',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'TSKeywordReturn',
    type = 'group',
    data = {
      fg = '#EB0075',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'TSPunctBracket',
    type = 'group',
    data = {
      fg = '#B3B3B3',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'TSStrong',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'bold',
      blend = 'NONE'
    }
  }, {
    name = 'TSEmphasis',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'italic',
      blend = 'NONE'
    }
  }, {
    name = 'TSUnderline',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'underline',
      blend = 'NONE'
    }
  }, {
    name = 'CmpItemAbbrDeprecated',
    type = 'group',
    data = {
      fg = '#FF120A',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'strikethrough',
      blend = 'NONE'
    }
  }, {
    name = 'Constant',
    type = 'group',
    data = {
      fg = '#FD30A4',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'IncSearch',
    type = 'group',
    data = {
      fg = '#CDFA05',
      bg = '#293201',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'CmpItemAbbrMatchFuzzy',
    type = 'group',
    data = {
      fg = '#FD30A4',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'Operator',
    type = 'group',
    data = {
      fg = '#4D4D4D',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'TelescopeMatching',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'TelescopeSelection',
    type = 'group',
    data = {
      fg = '#FD30A4',
      bg = 'none',
      sp = 'NONE',
      gui = 'bold',
      blend = 'NONE'
    }
  }, {
    name = 'Error',
    type = 'group',
    data = {
      fg = '#FF120A',
      bg = '#330200',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'WarningMsg',
    type = 'group',
    data = {
      fg = '#FF6600',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'TelescopeNormal',
    type = 'group',
    data = {
      fg = '#999999',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'CmpItemAbbrMatch',
    type = 'group',
    data = {
      fg = '#EB0075',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'DiagnosticInfo',
    type = 'group',
    data = {
      fg = '#F7CF1D',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'LspFloatWinBorder',
    type = 'group',
    data = {
      fg = '#E6E6E6',
      bg = 'none',
      sp = 'NONE',
      gui = 'NONE',
      blend = 'NONE'
    }
  }, {
    name = 'SpecialChar',
    type = 'group',
    data = {
      fg = '#F7CF1D',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'bold',
      blend = 'NONE'
    }
  }, {
    name = 'Underlined',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'underline',
      blend = 'NONE'
    }
  }, {
    name = 'Italic',
    type = 'group',
    data = {
      fg = 'NONE',
      bg = 'NONE',
      sp = 'NONE',
      gui = 'italic',
      blend = 'NONE'
    }
  }
}
local lush_apply = function(groups, opts)
  -- we may not always get given any options, so act safely
  local options = opts or {}
  -- configure_group(group) -> group
  --
  -- Accepts a group table (group.name, group.type (link or group) and
  -- group.data (table of fg, bg, gui, sp and blend)). Should return the group
  -- data with any desired alterations.
  --
  -- By default we make no modifications.
  local configure_group = options.configure_group_fn or function(group)
    -- by default don't modify anything
    return group
  end
  -- generate_group(group) -> any
  --
  -- Accepts a group table (group.name, group.type (link or group) and
  -- group.data (table of fg, bg, gui, sp and blend)). Should return something
  -- which apply() knows how to handle.
  --
  -- By default we generate a vimscript highlight rule.
  local generate_group = options.generate_group_fn or function(group)
    if group.type == 'link' then
      return string.format('highlight! link %s %s', group.name, group.data.to)
    elseif group.type == 'group' then
      return string.format(
                 'highlight! %s guifg=%s guibg=%s guisp=%s gui=%s blend=%s',
                 group.name, group.data.fg, group.data.bg, group.data.sp,
                 group.data.gui, group.data.blend)
    else
      error('unknown group type: ' .. group.type .. ' for group ' .. group.name)
    end
  end
  -- before_apply(any) -> any
  --
  -- Accepts a list of each group's result from generate_group_fn. Should
  -- return something apply_fn can understand.
  --
  -- By default, generate_group_fn returns a vimscript "highlight ..." command and
  -- apply_fn assumes it's recieving a list of commands to pass to vim.cmd, but
  -- you could for example, return a table of functions here and the apply_fn
  -- could call those functions.
  local before_apply = options.before_apply_fn or function(rules)
    -- just add the hi clear call
    table.insert(rules, 1, 'highlight clear')
    return rules
  end
  -- apply(any) -> any
  --
  -- Accepts a list of something and does something with it.
  --
  -- By default we assume generate_group_fn has created a highlight
  -- rule for each group and we can simply pass those on to the vim
  -- interpreter.
  local apply = options.apply_fn or function(rules)
    -- just send all the rules through to vim
    for _, cmd in ipairs(rules) do vim.api.nvim_command(cmd) end
  end
  local rules = {}
  for _, group in ipairs(groups) do
    group = configure_group(group)
    table.insert(rules, generate_group(group))
  end
  rules = before_apply(rules)
  return apply(rules)
end
-- PATCH_CLOSE

local overrides = {
  Comment = {
    italic = false
  }
}

local setup = function(config)
  if config.italic_comments then overrides['Comment']['italic'] = true end

  local my_configure_group = function(group)
    if overrides[group.name] then
      if overrides[group.name]['italic'] then
        -- apply configured override
        group.gui = 'italic'
      end
    end

    -- return maybe adjusted group
    return group
  end

  -- run lush loader with our custom configure function to
  -- adjust the groups per user config.
  lush_apply(lush_groups, {
    configure_group_fn = my_configure_group
  })
end

return {
  setup = setup
}
